### ISSUE TITLE
Release zip only contains rftd file.

### ISSUE THREAD

**Issue by dragonfax** [chuchusoft/Sequential#3]

**Comment by gingerbeardman** [comment]
As mentioned elsewhere, you need to read the readme.

> Release zip only contains rftd file.

@dragonfax it's weird, if you read the rftd it contains an embedded zip inside, which is the app! Plus installation instructions. A very weird way to release it.

![image](https://user-images.githubusercontent.com/49612/226756339-50d89d8e-6c83-488e-a6f2-e39d3e2d7af7.png)

**Comment by gmarinov** [comment]
https://github.com/chuchusoft/Sequential/blob/6ad52935d241b3dd4ddca7dd42e6cf497728c2ef/History.txt#L13-L14

**Comment by chuchusoft** [comment]
This is intentional (app bundle is self-signed and not notarised).

**Comment by gingerbeardman** [comment]
I don't see how it helps at all.

At least have a dmg for those users who would prefer it (basically 98% of people)
